name: Changelog Versioning Workflow

on:
  push:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Count commits
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "Commit count: $COMMIT_COUNT"
