name: Changelog Versioning Workflow

on:
  push:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
        
    - name: Create new branch
      run:|
      CURRENT_DATE=`date +%Y.%m.%d`
      BRANCH_NAME="version/$CURRENT_DATE"
      git checkout -b $BRANCH_NAME
