name: Changelog Versioning Workflow

on:
  push:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create new branch
      run: |
        BRANCH_NAME=$(date +"%Y-%m-%d")
        git pull ...
        git branch $BRANCH_NAME
        git checkout -b $BRANCH_NAME
        git push -u origin $BRANCH_NAME
