name: Changelog Versioning Workflow

on:
  push:
    branches:
      - main

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create new branch
      run: |
        BRANCH_NAME=$(date +"%Y-%m-%d")
        git fetch
        git branch $BRANCH_NAME
        git checkout $BRANCH_NAME
        git push -u origin $BRANCH_NAME

    - name: Update Changelog
      run: |
        echo "<h1> Changelog</h1>" >> CHANGELOG
        echo "- $(date +"%Y-%m-%d") - $(git log --format=%B -n 1)" >> CHANGELOG
        echo "## Changelog" >> CHANGELOG.md
        echo "- $(date +"%Y-%m-%d") - $(git log --format=%B -n 1)" >> CHANGELOG.md
